# -*- coding: utf-8 -*-
"""2. Árbol AVL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HGnNF3yxpip25aJ1sAXMYaxAJBZKnzdI

# Árbol AVL

Árbol AVL nos sirve para almacenar información ordenada con el fin de optimizar la búsqueda de elementos siguiendo las reglas de un BST pero considerando el factor de balanceo, el cual debe estar en el conjunto de datos {-1, 0 , 1}.

EL factor de balanceo se calcula así:

hHijoIzq = altura del hijo izquierdo
hHijoDerecho = altura del hijo derecho

fb = hHijoIzq - hHijoDerecho

El código mermaid (https://mermaid.ai/) para el diagrama es:

    class NodoAVL {
        +int valor
        +int altura
        +Nodo izquierda
        +Nodo derecha
        +Nodo(int valor)   
        +getAltura()
        +setALtura(h)     
    }
    
    class ArbolAVL {
        +Nodo raiz
        +ArbolAVL()
        +void insertar(int valor)
        +boolean buscar(int valor)
        +void eliminar(int valor)
        +void recorridoInorden()
        +void recorridoPreorden()
        +void recorridoPostorden()
        +void actualizarActura()
        +int calcularFactorDeBalanceo()
    }
    
    ArbolBST --> Nodo : contiene

## Clase Nodo

Clase que sirve para construir un nodo y definir todos sus atributos y operaciones.
"""

class NodoAVL:

  def __init__(self, valor):

    self.valor = valor
    self.altura = 0
    self.hijoIzquierdo = None
    self.hijoDerecho = None
    self.padre = None

  def getAltura(self):
    return self.altura

  def setAltura(self, h):
    self.altura = h

  def getValor(self):
    return self.valor


  def setValor(self, valor):
    self.valor = valor


  def getHijoIzquierdo(self):
    return self.hijoIzquierdo


  def setHijoIzquierdo(self, nodo):
    self.hijoIzquierdo = nodo


  def getHijoDerecho(self):
    return self.hijoDerecho


  def setHijoDerecho(self, nodo):
    self.hijoDerecho = nodo


  def getPadre(self):
    return self.padre


  def setPadre(self, nodo):
    self.padre = nodo

"""## Clase ArbolAVL

Sirve para definir el árbol y sus operaciones. Solo tendrá el atributo del nodo raiz.
"""

class ArbolBST:

  def __init__(self):
    self.raiz = None


  # --------------------------------------------------
  # INSERTAR
  # --------------------------------------------------

  # método público de insertar
  def insertar(self, dato):

    nodo = NodoAVL(dato)

    if self.raiz is None:

      self.raiz = nodo

      # la raíz no tiene padre
      nodo.setPadre(None)

      print(
        "El valor ",
        dato,
        " se ha insertado como raíz del árbol"
      )

    else:

      self._insertar(
        nodo,
        self.raiz
      )


  # método privado de insertar
  def _insertar(self, nodo, raizActual):

    # se valida igualdad
    if raizActual.getValor() == nodo.getValor():

      print(
        "Ya existe un nodo con valor ",
        nodo.getValor()
      )

    else:

      # si es menor se va por la izquierda
      if nodo.getValor() < raizActual.getValor():

        izq = raizActual.getHijoIzquierdo()

        if izq is None:

          raizActual.setHijoIzquierdo(nodo)

          # se establece el padre
          nodo.setPadre(raizActual)

          print(
            nodo.getValor(),
            " se ha insertado como hijo izquierdo de ",
            raizActual.getValor()
          )

        else:

          self._insertar(
            nodo,
            izq
          )


      # si es mayor se va por la derecha
      else:

        der = raizActual.getHijoDerecho()

        if der is None:

          raizActual.setHijoDerecho(nodo)

          # se establece el padre
          nodo.setPadre(raizActual)

          print(
            nodo.getValor(),
            " se ha insertado como hijo derecho de ",
            raizActual.getValor()
          )

        else:

          self._insertar(
            nodo,
            der
          )


  # --------------------------------------------------
  # BUSCAR
  # --------------------------------------------------

  # método público de buscar
  def buscar(self, dato):

    if self.raiz is None:

      print("El árbol está vacío")

      return None

    else:

      return self._buscar(
        dato,
        self.raiz
      )


  # método privado de buscar
  def _buscar(self, dato, raizActual):

    if dato == raizActual.getValor():

      return raizActual


    if dato < raizActual.getValor():

      izq = raizActual.getHijoIzquierdo()

      if izq is None:

        return None

      else:

        return self._buscar(
          dato,
          izq
        )


    else:

      der = raizActual.getHijoDerecho()

      if der is None:

        return None

      else:

        return self._buscar(
          dato,
          der
        )


  def anchura (self):
    if self.raiz is None:
      print("El árbol está vacío")
      return []
    else:
      return self._anchura(self.raiz)

  def _anchura(self, raizActual):
    cola = []
    recorrido = []
    cola.append(raizActual)
    while len(cola) > 0:
      nodo = cola.pop(0)
      recorrido.append(nodo)
      if nodo.getHijoIzquierdo() is not None:
        cola.append(nodo.getHijoIzquierdo())
      if nodo.getHijoDerecho() is not None:
        cola.append(nodo.getHijoDerecho())

    return recorrido

  # --------------------------------------------------
  # RECORRIDO PREORDEN
  # raíz - izquierda - derecha
  # --------------------------------------------------

  def preorden(self):

    if self.raiz is None:

      print("El árbol está vacío")

    else:

      self._preorden(
        self.raiz
      )


  def _preorden(self, raizActual):

    if raizActual is not None:

      print(
        raizActual.getValor()
      )

      self._preorden(
        raizActual.getHijoIzquierdo()
      )

      self._preorden(
        raizActual.getHijoDerecho()
      )


  # --------------------------------------------------
  # RECORRIDO INORDEN
  # izquierda - raíz - derecha
  # --------------------------------------------------

  def inorden(self):

    if self.raiz is None:

      print("El árbol está vacío")

    else:

      self._inorden(
        self.raiz
      )


  def _inorden(self, raizActual):

    if raizActual is not None:

      self._inorden(
        raizActual.getHijoIzquierdo()
      )

      print(
        raizActual.getValor()
      )

      self._inorden(
        raizActual.getHijoDerecho()
      )


  # --------------------------------------------------
  # RECORRIDO POSORDEN
  # izquierda - derecha - raíz
  # --------------------------------------------------

  def posorden(self):

    if self.raiz is None:

      print("El árbol está vacío")

    else:

      self._posorden(
        self.raiz
      )


  def _posorden(self, raizActual):

    if raizActual is not None:

      self._posorden(
        raizActual.getHijoIzquierdo()
      )

      self._posorden(
        raizActual.getHijoDerecho()
      )

      print(
        raizActual.getValor()
      )


  # --------------------------------------------------
  # ELIMINAR
  # --------------------------------------------------

  # método público de eliminar
  def eliminar(self, dato):

    if self.raiz is None:

      print("El árbol está vacío")

    else:

      nodo = self.buscar(dato)

      if nodo is None:

        print(
          "No existe un nodo con valor ",
          dato
        )

      else:

        self._eliminar(
          nodo
        )

        print(
          "Se eliminó el nodo ",
          dato
        )


  # método privado de eliminar
  def _eliminar(self, nodo):

    # ------------------------------------------------
    # CASO 1
    # el nodo es una hoja
    # ------------------------------------------------

    if (
      nodo.getHijoIzquierdo() is None
      and
      nodo.getHijoDerecho() is None
    ):

      padre = nodo.getPadre()

      # si el nodo es la raíz
      if padre is None:

        self.raiz = None

      else:

        # se determina si es hijo izquierdo
        if padre.getHijoIzquierdo() == nodo:

          padre.setHijoIzquierdo(None)

        # de lo contrario es hijo derecho
        else:

          padre.setHijoDerecho(None)

      nodo.setPadre(None)

      return


    # ------------------------------------------------
    # CASO 2
    # solamente tiene hijo derecho
    # ------------------------------------------------

    if nodo.getHijoIzquierdo() is None:

      hijo = nodo.getHijoDerecho()
      padre = nodo.getPadre()

      # si el nodo es la raíz
      if padre is None:

        self.raiz = hijo

        hijo.setPadre(None)

      else:

        # si el nodo es hijo izquierdo
        if padre.getHijoIzquierdo() == nodo:

          padre.setHijoIzquierdo(hijo)

        else:

          padre.setHijoDerecho(hijo)

        # el hijo ahora apunta al padre del nodo eliminado
        hijo.setPadre(padre)

      nodo.setPadre(None)
      nodo.setHijoDerecho(None)

      return


    # ------------------------------------------------
    # CASO 2
    # solamente tiene hijo izquierdo
    # ------------------------------------------------

    if nodo.getHijoDerecho() is None:

      hijo = nodo.getHijoIzquierdo()
      padre = nodo.getPadre()

      # si el nodo es la raíz
      if padre is None:

        self.raiz = hijo

        hijo.setPadre(None)

      else:

        # si el nodo es hijo izquierdo
        if padre.getHijoIzquierdo() == nodo:

          padre.setHijoIzquierdo(hijo)

        else:

          padre.setHijoDerecho(hijo)

        # el hijo ahora apunta al padre del nodo eliminado
        hijo.setPadre(padre)

      nodo.setPadre(None)
      nodo.setHijoIzquierdo(None)

      return


    # ------------------------------------------------
    # CASO 3
    # el nodo tiene dos hijos
    #
    # se utiliza el PREDECESOR
    # ------------------------------------------------

    predecesor = self._getPredecesor(
      nodo
    )

    # se copia el valor del predecesor
    # en el nodo que se desea eliminar
    nodo.setValor(
      predecesor.getValor()
    )

    # se elimina físicamente el predecesor
    self._eliminar(
      predecesor
    )


  # --------------------------------------------------
  # OBTENER PREDECESOR
  #
  # retorna el mayor nodo del subárbol izquierdo
  # --------------------------------------------------

  def _getPredecesor(self, nodo):

    actual = nodo.getHijoIzquierdo()

    while actual.getHijoDerecho() is not None:

      actual = actual.getHijoDerecho()

    return actual


  # --------------------------------------------------
  # DIBUJAR
  # --------------------------------------------------

  def dibujar(self):

    if self.raiz is None:

      print("El árbol está vacío")

    else:

      print("\nÁrbol BST:")
      print("-----------")

      self._dibujar(
        self.raiz,
        "",
        "R"
      )

  # obtener la altura de un nodo
  def _altura(self, nodo):
    if nodo is None:
      return -1
    else:
      return nodo.getAltura()

  # actualizar la altura de un nodo
  def _actualizarAltura(self, nodo):
    hIzq = self._altura(nodo.getHijoIzquierdo())
    hDer = self._altura(nodo.getHijoDerecho())
    hMax = max(hIzq, hDer)
    nodo.setAltura(
        hMax + 1
    )


  # ---------------------------------------------
  # GIRO SIMPLE A LA IZQUIERDA (RR)
  # ---------------------------------------------
  def _giroSimpleIzquierda(self, superior):
    # se obtiene el nodo de la mitad
    mitad = superior.getHijoDerecho()

    # Se hace el giro a la izquierda
    hijoIzqMitad = mitad.getHijoIzquierdo()
    padreSuperior = superior.getPadre()
    mitad.setHijoIzquierdo(superior)
    superior.setPadre(mitad)
    mitad.setPadre(padreSuperior)
    superior.setHijoDerecho(hijoIzqMitad)
    # asignar a mitad como hijo del anterior padre de superior
    if padreSuperior is not None:
      if padreSuperior.getValor() > superior.getValor():
        padreSuperior.setHijoIzquierdo(mitad)
      else:
        padreSuperior.setHijoDerecho(mitad)


  # ---------------------------------------------
  # GIRO SIMPLE A LA DERECHA (LL)
  # ---------------------------------------------
  def _giroSimpleDerecha(self, superior):
    # se obtiene el nodo de la mitad
    mitad = superior.getHijoIzquierdo()

    # Se hace el giro a la derecha
    hijoDerMitad = mitad.getHijoDerecho()
    padreSuperior = superior.getPadre()
    mitad.setHijoDerecho(superior)
    superior.setPadre(mitad)
    mitad.setPadre(padreSuperior)
    superior.setHijoIzquierdo(hijoDerMitad)
    # asignar a mitad como hijo del anterior padre de superior
    if padreSuperior is not None:
      if padreSuperior.getValor() > superior.getValor():
        padreSuperior.setHijoIzquierdo(mitad)
      else:
        padreSuperior.setHijoDerecho(mitad)

  # Detectar el desbalanceo
  def _calcularFactorDeBalanceo(self, nodo):
    hIzq = 0
    hDer = 0

    if nodo.getHijoIzquierdo() is not None:
      self._actualizarAltura(nodo.getHijoIzquierdo())
      hIzq = nodo.getHijoIzquierdo().getAltura()

    if nodo.getHijoDerecho() is not None:
      self._actualizarAltura(nodo.getHijoDerecho())
      hDer = nodo.getHijoDerecho().getAltura()

    fb = hIzq - hDer
    return fb

  # Detectar caso de desbalanceo
  def _detectarCasoDesbalanceo(self, superior, fb):
    caso = ""
    if fb > 0: # la primera es L
      fbHijo = self._calcularFactorDeBalanceo(superior.getHijoIzquierdo())
      if fbHijo > 0: # la segunda es L
        caso = "LL"
      else: # segunda es R
        caso = "LR"
    else: # primera es R
      fbHijo = self._calcularFactorDeBalanceo(superior.getHijoDerecho())
      if fbHijo > 0: # la segunda es L
        caso = "RL"
      else: # segunda es R
        caso = "RR"

  # método de balanceo
  def _balancear(self, superior, caso):
    match(caso):
      case "LL":
        self._giroSimpleDerecha(superior)
      case "RR"
        self._giroSimpleIzquierda(superior)
      case "LR":
        self._giroSimpleIzquierda(superior.getHijoIzquierdo())
        self._giroSimpleDerecha(superior)
      case "RL":
        self._giroSimpleDerecha(superior.getHijoDerecho())
        self._giroSimpleIzquierda(superior)


  # método para dibujar conceptualmente el árbol binario
  def _dibujar(self, raizActual, espacio, posicion):

    if raizActual is not None:

      self._dibujar(
        raizActual.getHijoDerecho(),
        espacio + "     ",
        "D"
      )

      print(
        espacio +
        posicion + "── " +
        str(raizActual.getValor())
      )

      self._dibujar(
        raizActual.getHijoIzquierdo(),
        espacio + "     ",
        "I"
      )

lista = [32, 76, 100, 25, 4, 1, 50]
arbol = ArbolBST()
for n in lista:
  arbol.insertar(n)

nodoEncontrado = arbol.buscar(32)
if nodoEncontrado is not None:
  print(nodoEncontrado.getValor())

"""## Recorridos

1. Anchura
2. Profundidad:
 - Preorden (RID)
 - Inorden (IRD)
 - Posorden (IDR)
"""

recorrido = arbol.anchura()
for n in recorrido:
  print(n.getValor())

recorrido = arbol.preorden()
for n in recorrido:
  print(n.getValor())

